Repository ankh-is/localstack, pull requests merged in 2021-03, with the labels that each got.

#2 Try to set up an ingress for localstack
  charts/localstack/values.yaml
  jx-requirements.yml
Labels: size/S

#5 trying a custom dockerfile with tasks docker-helm
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Dockerfile
  charts/localstack/Chart.yaml
  charts/localstack/values.yaml
Labels: size/S

#6 enable ingress
  charts/localstack/Chart.yaml
  charts/localstack/values.yaml
Labels: size/XS

#7 try setting a host for the endpoint?
  charts/localstack/Chart.yaml
  charts/localstack/values.yaml
Labels: size/XS

#8 Copy py py test ingress template
  charts/localstack/Chart.yaml
  charts/localstack/templates/ingress.yaml
  charts/localstack/values.yaml
Labels: approve, size/M
